apiVersion: v1
kind: Service
metadata:
  name: resume-builder-model-api-svc
  namespace: plasma-namespace
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app-name: resume-builder-model-api